import { createPost } from "../model/createPost";
import { tagsMocks } from "entities/tag";
import post1 from "@/shared/icons/pivo.jpg";
import post2 from "@/shared/icons/pivo.jpg";
import post3 from "@/shared/icons/pivo.jpg";
import ava2 from "@/shared/icons/pivo.jpg";
import ava1 from "@/shared/icons/pivo.jpg";

export const galleryPostsMock = [
    createPost({
        id: 1,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post1,
        date: "2020-05-14T08:00:00.00Z",
        title: "Сияние города1",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 2,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post2,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой11",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Арт с городской эстетикой",
        tags: []
    }),
    createPost({
        id: 3,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post3,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города111",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 4,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post2,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой1111",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифровая картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 5,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой11111",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифровая картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 6,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post1,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города111111",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая картина в неоновоadsaffafaffaraм стиле",
        tags: []
    }),
    createPost({
        id: 7,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой1111111",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифровая vaffартина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 8,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post1,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города11111111",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 9,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post2,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города11111111",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая каvffasvavртина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 10,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой111111111",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 11,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой1111111111",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 12,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой111111111111",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 13,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post2,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города0",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая каvffasvavртина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 14,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой00",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 15,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой000",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 16,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой0000",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 17,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post2,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города00000",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая каvffasvavртина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 18,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой000000",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 19,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой0000000",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 20,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой00000000",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 21,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post2,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города000000000",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая каvffasvavртина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 22,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой0000000000",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 23,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой00000000000",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 24,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой000000000000",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 25,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post2,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города2",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая каvffasvavртина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 26,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой22",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 27,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой222",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 28,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой2222",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 29,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post2,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города22222",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая каvffasvavртина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 30,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой222222",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 31,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой2222222",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 32,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой22222222",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 33,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post2,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города222222222",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая каvffasvavртина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 34,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой2222222222",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 35,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой22222222222",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 36,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой222222222222",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 37,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post2,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города3",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая каvffasvavртина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 38,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой33",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 39,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой333",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 40,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой3333",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    })
];

export const profilePostsMock = [
    createPost({
        id: 1,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post1,
        date: "2020-05-14T08:00:00.00Z",
        title: "Сияние города1",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 2,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post2,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой11",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Арт с городской эстетикой",
        tags: []
    }),
    createPost({
        id: 3,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post3,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города111",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 4,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post2,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой1111",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифровая картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 5,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой11111",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифровая картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 6,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post1,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города111111",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая картина в неоновоadsaffafaffaraм стиле",
        tags: []
    }),
    createPost({
        id: 7,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой1111111",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифровая vaffартина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 8,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post1,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города11111111",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 9,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post2,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города11111111",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая каvffasvavртина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 10,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой111111111",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 11,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой1111111111",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 12,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой111111111111",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 13,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post2,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города0",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая каvffasvavртина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 14,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой00",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 15,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой000",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 16,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой0000",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 17,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post2,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города00000",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая каvffasvavртина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 18,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой000000",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 19,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой0000000",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 20,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой00000000",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    })
];

export const communityPostsMock = [
    createPost({
        id: 1,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post1,
        date: "2020-05-14T08:00:00.00Z",
        title: "Сияние города1",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 2,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post2,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой11",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Арт с городской эстетикой",
        tags: []
    }),
    createPost({
        id: 3,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post3,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города111",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 4,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post2,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой1111",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифровая картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 5,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой11111",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифровая картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 6,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post1,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города111111",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая картина в неоновоadsaffafaffaraм стиле",
        tags: []
    }),
    createPost({
        id: 7,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой1111111",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифровая vaffартина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 8,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post1,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города11111111",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 9,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post2,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города11111111",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая каvffasvavртина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 10,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой111111111",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 11,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой1111111111",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 12,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой111111111111",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 13,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post2,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города0",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая каvffasvavртина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 14,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой00",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 15,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой000",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 16,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой0000",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 17,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post2,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города00000",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая каvffasvavртина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 18,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой000000",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 19,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой0000000",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 20,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой00000000",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 21,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post2,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города000000000",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая каvffasvavртина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 22,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой0000000000",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 23,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой00000000000",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 24,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой000000000000",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 25,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post2,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города2",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая каvffasvavртина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 26,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой22",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 27,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой222",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 28,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой2222",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 29,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post2,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города22222",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая каvffasvavртина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 30,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой222222",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 31,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой2222222",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 32,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой22222222",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 33,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post2,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города222222222",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая каvffasvavртина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 34,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой2222222222",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 35,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой22222222222",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 36,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой222222222222",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 37,
        likes: 0,
        comments: 1,
        reposts: 0,
        srcImg: post2,
        date: "2025-05-14T08:00:00.00Z",
        title: "Сияние города3",
        authorId: 1,
        authorName: "Анна",
        authorUserName: "",
        srcAuthor: ava1,
        description: "Цифровая каvffasvavртина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 38,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой33",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 39,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой333",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    }),
    createPost({
        id: 40,
        likes: 1,
        comments: 1,
        reposts: 1,
        srcImg: post3,
        date: "2025-05-13T08:00:00.00Z",
        title: "Туман над рекой3333",
        authorId: 2,
        authorName: "Марк",
        authorUserName: "",
        srcAuthor: ava2,
        description: "Цифроваvsdfvsdя картина в неоновом стиле",
        tags: []
    })
];

export const postMock = createPost({
    id: 21,
    title: "Название поста",
    description: "Здесь будет описание работы, вдохновение автора и т.п.",
    srcImg: post1,
    authorId: 3,
    authorName: "Автор аылоаврышраыры",
    srcAuthor: ava1,
    authorUserName: "artist_name",
    likes: 10000,
    comments: 5,
    reposts: 1000,
    date: "2025-05-13T08:00:00.00Z",
    tags: tagsMocks
});
