import {createPost} from "../model/createPost";
import img from "shared/icons/img-CTA.jpg";
import {profileUserMock} from "../../user";

export const profileAlbum1PostsMock = [
    createPost({
        id: 1,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAB",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z"
    }),
    createPost({
        id: 1,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAV",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z"
    }),
    createPost({
        id: 2,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAU",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z"
    }),
    createPost({
        id: 3,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAA",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z"
    }),
];

export const profileAlbum2PostsMock = [
    createPost({
        id: 6,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAB",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z"
    }),
    createPost({
        id: 1,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAV",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z"
    }),
    createPost({
        id: 2,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAU",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z"
    }),
    createPost({
        id: 3,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAA",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z"
    }),
    createPost({
        id: 4,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAv",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z"
    }),
    createPost({
        id: 3,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAA",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z"
    }),
    createPost({
        id: 4,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAv",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z"
    }),
];
